//! Lyric cleanup pass (PLAN.md §3): pasted lyrics arrive dirty — Genius /
//! AZLyrics style section headers, "(x2)" repeat markers, parenthetical
//! ad-libs, credit lines. This stage runs **before** alignment and decides
//! *what words exist*; the alignment normalization ([`crate::alignment::anchor`])
//! decides *how they are matched*. Charset folding is deliberately not
//! duplicated here.
//!
//! Rules (PLAN.md §3, §4):
//! - section headers (`[Chorus]`, `[Verse 2]`, `[Bridge: Artist]`, `(Chorus)`,
//!   bare `Chorus:` lines) are **stripped**
//! - repeat markers (`(x2)`, `x2`, `(2x)`, `[x3]`, `×2`) are **expanded** —
//!   on a line, on a stanza (lone marker line), or on a section (marker in a
//!   header) — with provenance kept on the generated lines
//! - parenthetical ad-libs (`(oh yeah)`) are **flagged, kept** — alignment may
//!   place them, display can style them differently
//! - credit / boilerplate lines ("Produced by …", "© …", Genius embed junk)
//!   are **stripped**
//! - everything kept preserves its display text **verbatim**; a clean input
//!   reconstructs byte-identical via [`CleanLyrics::to_text`]
//!
//! Every change is recorded in [`CleanLyrics::edits`] with source-line
//! references, and [`CleanLyrics::summary`] renders the one-line human form
//! ("removed 4 section headers, expanded one x2 chorus" — PLAN.md §4). The
//! default requires no decisions.

use serde::Serialize;

use crate::alignment::anchor;
use crate::error::{Error, Result};
use crate::timing::WordTimingMap;

/// Repeat counts are clamped here — "(x99)" in pasted junk must not explode
/// the song.
pub const MAX_REPEAT: u32 = 8;

/// Section-header keywords (lowercase). A bracketed or `Keyword:` line whose
/// spec starts with one of these is a header, optionally followed by a number
/// ("Verse 2"), an artist ("Bridge: Artist"), and/or a repeat marker
/// ("Chorus x2").
const SECTION_KEYWORDS: &[&str] = &[
    "intro",
    "verse",
    "chorus",
    "pre-chorus",
    "prechorus",
    "post-chorus",
    "postchorus",
    "hook",
    "bridge",
    "refrain",
    "outro",
    "interlude",
    "instrumental",
    "solo",
    "break",
    "breakdown",
    "drop",
    "part",
];

/// One kept word. Display text is verbatim (including any parentheses).
#[derive(Debug, Clone, Serialize)]
pub struct CleanWord {
    pub display: String,
    /// Parenthetical ad-lib — alignment may place it, display may style it.
    pub ad_lib: bool,
}

/// One kept lyric line. Lines matter downstream: LRC/ASS/UltraStar exporters
/// are line-oriented.
#[derive(Debug, Clone, Serialize)]
pub struct CleanLine {
    /// Verbatim kept text (only removed markers/suffixes are gone).
    pub display: String,
    pub words: Vec<CleanWord>,
    /// 1-based line number in the pasted input this line came from.
    pub source_line: usize,
    /// Blank lines between the previous kept line and this one (stanza
    /// structure, preserved for reconstruction and exporters).
    pub blank_before: usize,
    /// True when this line was generated by repeat expansion (provenance:
    /// `source_line` then points at the line it is a copy of).
    pub repeated: bool,
}

/// What a repeat marker applied to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RepeatScope {
    /// Marker trailing a lyric line — that line repeats.
    Line,
    /// Lone marker line — the stanza above it repeats.
    Stanza,
    /// Marker inside a section header — the section below repeats.
    Section,
}

/// One recorded edit, with a source-line reference. Machine-readable change
/// summary (PLAN.md §4).
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Edit {
    SectionHeaderRemoved {
        line: usize,
        text: String,
    },
    CreditLineRemoved {
        line: usize,
        text: String,
    },
    /// Genius paste junk glued to the last line ("…goodbye42Embed").
    EmbedSuffixRemoved {
        line: usize,
        text: String,
    },
    RepeatExpanded {
        /// Source line the marker sat on.
        line: usize,
        /// The marker exactly as pasted (e.g. "(x2)").
        marker: String,
        times: u32,
        scope: RepeatScope,
        /// Section name when the marker was in a header (e.g. "chorus").
        section: Option<String>,
        /// Lines added to the output by this expansion.
        lines_added: usize,
    },
    AdLibFlagged {
        line: usize,
        text: String,
    },
}

impl std::fmt::Display for Edit {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Edit::SectionHeaderRemoved { line, text } => {
                write!(f, "line {line}: removed section header \"{text}\"")
            }
            Edit::CreditLineRemoved { line, text } => {
                write!(f, "line {line}: removed credit/boilerplate \"{text}\"")
            }
            Edit::EmbedSuffixRemoved { line, text } => {
                write!(f, "line {line}: removed embed tag \"{text}\"")
            }
            Edit::RepeatExpanded {
                line,
                marker,
                times,
                scope,
                section,
                lines_added,
            } => {
                let what = match (scope, section) {
                    (RepeatScope::Section, Some(name)) => name.clone(),
                    (RepeatScope::Section, None) => "section".into(),
                    (RepeatScope::Stanza, _) => "stanza".into(),
                    (RepeatScope::Line, _) => "line".into(),
                };
                write!(
                    f,
                    "line {line}: expanded {marker} — {what} x{times} (+{lines_added} line(s))"
                )
            }
            Edit::AdLibFlagged { line, text } => {
                write!(f, "line {line}: flagged ad-lib \"{text}\" (kept)")
            }
        }
    }
}

/// Cleanup output: kept line/word structure + the edit log.
#[derive(Debug, Clone, Serialize)]
pub struct CleanLyrics {
    pub lines: Vec<CleanLine>,
    pub edits: Vec<Edit>,
    #[serde(skip)]
    trailing_newline: bool,
}

impl CleanLyrics {
    /// Reconstruct the cleaned text. When the input needed no edits this is
    /// byte-identical to the input (CRLF inputs come back LF — the one
    /// normalization applied unconditionally).
    pub fn to_text(&self) -> String {
        let mut out = String::new();
        for (i, line) in self.lines.iter().enumerate() {
            if i > 0 {
                out.push('\n');
            }
            for _ in 0..line.blank_before {
                out.push('\n');
            }
            out.push_str(&line.display);
        }
        if self.trailing_newline && !self.lines.is_empty() {
            out.push('\n');
        }
        out
    }

    pub fn word_count(&self) -> usize {
        self.lines.iter().map(|l| l.words.len()).sum()
    }

    /// Flatten to the aligner's input words. Norms come from
    /// [`anchor::normalize_word`] — cleanup never duplicates that folding.
    pub fn lyric_words(&self) -> Vec<anchor::LyricWord> {
        self.lines
            .iter()
            .flat_map(|l| l.words.iter())
            .map(|w| anchor::LyricWord {
                display: w.display.clone(),
                norm: anchor::normalize_word(&w.display),
            })
            .collect()
    }

    /// Stamp lyric line/word indices and ad-lib flags onto a timing map whose
    /// words came 1:1 from [`Self::lyric_words`]. This is the stable link
    /// between the timing map and the lyric structure (exporters are
    /// line-oriented).
    pub fn annotate_map(&self, map: &mut WordTimingMap) -> Result<()> {
        if self.word_count() != map.words.len() {
            return Err(Error::InvalidInput(format!(
                "timing map has {} words but cleaned lyrics have {} — map was not built from these lyrics",
                map.words.len(),
                self.word_count()
            )));
        }
        let mut k = 0usize;
        for (li, line) in self.lines.iter().enumerate() {
            for (wi, w) in line.words.iter().enumerate() {
                map.words[k].line = Some(li);
                map.words[k].word_in_line = Some(wi);
                map.words[k].ad_lib = w.ad_lib;
                k += 1;
            }
        }
        Ok(())
    }

    /// One-line human rendering of the edit log (PLAN.md §4:
    /// "removed 4 section headers, expanded one x2 chorus").
    pub fn summary(&self) -> String {
        let mut headers = 0usize;
        let mut credits = 0usize;
        let mut adlibs = 0usize;
        let mut repeats: Vec<(&u32, &RepeatScope, &Option<String>)> = Vec::new();
        for e in &self.edits {
            match e {
                Edit::SectionHeaderRemoved { .. } => headers += 1,
                Edit::CreditLineRemoved { .. } | Edit::EmbedSuffixRemoved { .. } => credits += 1,
                Edit::AdLibFlagged { .. } => adlibs += 1,
                Edit::RepeatExpanded {
                    times,
                    scope,
                    section,
                    ..
                } => repeats.push((times, scope, section)),
            }
        }
        let mut parts: Vec<String> = Vec::new();
        if headers > 0 {
            parts.push(format!(
                "removed {headers} section header{}",
                plural(headers)
            ));
        }
        if credits > 0 {
            parts.push(format!(
                "removed {credits} credit/boilerplate line{}",
                plural(credits)
            ));
        }
        match repeats.len() {
            0 => {}
            1 => {
                let (times, scope, section) = repeats[0];
                let what = match (scope, section) {
                    (RepeatScope::Section, Some(name)) => name.clone(),
                    (RepeatScope::Section, None) => "section".into(),
                    (RepeatScope::Stanza, _) => "stanza".into(),
                    (RepeatScope::Line, _) => "line".into(),
                };
                parts.push(format!("expanded one x{times} {what}"));
            }
            n => parts.push(format!("expanded {n} marked repeats")),
        }
        if adlibs > 0 {
            parts.push(format!("flagged {adlibs} ad-lib{}", plural(adlibs)));
        }
        if parts.is_empty() {
            "no changes needed".into()
        } else {
            parts.join(", ")
        }
    }
}

fn plural(n: usize) -> &'static str {
    if n == 1 {
        ""
    } else {
        "s"
    }
}

// ---------------------------------------------------------------------------
// token-level helpers (hand parsing, std only — no regex dependency)
// ---------------------------------------------------------------------------

/// "x2" / "2x" / "×3" / "3×" (case-insensitive), count clamped to
/// [`MAX_REPEAT`]. Counts below 2 are not markers.
fn parse_repeat_token(s: &str) -> Option<u32> {
    let s = s.trim();
    let n: u32 = if let Some(digits) = s
        .strip_prefix(['x', 'X'])
        .or_else(|| s.strip_prefix('\u{d7}'))
    {
        digits.parse().ok()?
    } else if let Some(digits) = s
        .strip_suffix(['x', 'X'])
        .or_else(|| s.strip_suffix('\u{d7}'))
    {
        digits.parse().ok()?
    } else {
        return None;
    };
    if (2..=99).contains(&n) {
        Some(n.min(MAX_REPEAT))
    } else {
        None
    }
}

/// A repeat marker possibly wrapped in one pair of `()` or `[]`.
fn parse_repeat_marker(s: &str) -> Option<u32> {
    let s = s.trim();
    let inner = strip_enclosing(s).map(|(_, i)| i).unwrap_or(s);
    parse_repeat_token(inner)
}

/// When `s` is fully enclosed in one balanced `[..]`, `(..)` or `{..}` pair,
/// return the bracket kind and inner text.
fn strip_enclosing(s: &str) -> Option<(char, &str)> {
    let s = s.trim();
    let open = s.chars().next()?;
    let close = match open {
        '[' => ']',
        '(' => ')',
        '{' => '}',
        _ => return None,
    };
    let (end, _) = matching_close(s, open, close)?;
    if end != s.len() - close.len_utf8() {
        return None; // closes before the end: not fully enclosed
    }
    Some((open, &s[open.len_utf8()..end]))
}

/// Byte index of the close bracket matching the open bracket at byte 0.
fn matching_close(s: &str, open: char, close: char) -> Option<(usize, usize)> {
    let mut depth = 0i32;
    for (i, c) in s.char_indices() {
        if c == open {
            depth += 1;
        } else if c == close {
            depth -= 1;
            if depth == 0 {
                return Some((i, i + close.len_utf8()));
            }
        }
    }
    None
}

fn is_number_token(t: &str) -> bool {
    !t.is_empty()
        && (t.chars().all(|c| c.is_ascii_digit())
            || t.chars().all(|c| matches!(c, 'i' | 'v' | 'x' | 'I' | 'V' | 'X')))
}

/// Parse a section spec like "Chorus", "Verse 2", "Pre-Chorus", "Chorus x2",
/// "Part II" -> (lowercased name, repeat count).
fn parse_section_spec(spec: &str) -> Option<(String, u32)> {
    let toks: Vec<&str> = spec.split_whitespace().collect();
    if toks.is_empty() {
        return None;
    }
    let t0 = toks[0].to_lowercase();
    let (name, rest) = if SECTION_KEYWORDS.contains(&t0.as_str()) {
        (t0, &toks[1..])
    } else if toks.len() >= 2
        && matches!(t0.as_str(), "pre" | "post")
        && toks[1].to_lowercase().starts_with("chorus")
    {
        (format!("{t0}-chorus"), &toks[2..])
    } else {
        return None;
    };
    let mut times = 1u32;
    for tok in rest {
        if is_number_token(tok) {
            continue; // section number ("Verse 2", "Part II")
        }
        if let Some(n) = parse_repeat_marker(tok) {
            times = n;
            continue;
        }
        return None;
    }
    Some((name, times))
}

/// Full header-line detection. Returns `(name, times, header_text)`.
/// Handles `[Chorus]`, `(Chorus)`, `{Hook}`, `[Verse 2: Artist]`,
/// `[Chorus x2]`, `[Chorus] (x2)`, and bare `Chorus:` / `Verse 2:` /
/// `Chorus: (x2)` lines.
fn parse_header_line(line: &str) -> Option<(String, u32)> {
    let t = line.trim();
    // bracketed (possibly with a trailing repeat marker outside the brackets)
    if let Some(open) = t.chars().next().filter(|c| matches!(c, '[' | '(' | '{')) {
        let close = match open {
            '[' => ']',
            '(' => ')',
            _ => '}',
        };
        let (_, after) = matching_close(t, open, close)?;
        let inner = &t[open.len_utf8()..after - close.len_utf8()];
        let rest = t[after..].trim();
        let spec = split_off_artist(inner);
        let (name, mut times) = parse_section_spec(spec)?;
        if !rest.is_empty() {
            times = parse_repeat_marker(rest)?; // "[Chorus] (x2)"
        }
        return Some((name, times));
    }
    // bare "Chorus:" / "Verse 2:" — conservative: requires the colon, and
    // anything after it must be a repeat marker (an artist tail on a bare
    // line is left alone; it could be a lyric)
    let (left, right) = t.split_once(':')?;
    let (name, mut times) = parse_section_spec(left)?;
    let right = right.trim();
    if !right.is_empty() {
        times = parse_repeat_marker(right)?;
    }
    Some((name, times))
}

/// "Verse 2: Artist" -> "Verse 2" (also handles " - Artist").
fn split_off_artist(inner: &str) -> &str {
    if let Some((l, _)) = inner.split_once(':') {
        return l;
    }
    if let Some(pos) = inner.find(" - ") {
        return &inner[..pos];
    }
    inner
}

/// Genuinely non-lyric credit / boilerplate lines (stripped, not flagged).
fn is_credit_line(line: &str) -> bool {
    let l = line.trim().to_lowercase();
    const PREFIXES: &[&str] = &[
        "lyrics by ",
        "written by ",
        "produced by ",
        "music by ",
        "words by ",
        "composed by ",
        "arranged by ",
        "mixed by ",
        "mastered by ",
        "performed by ",
        "published by ",
        "courtesy of ",
        "copyright",
        "\u{a9}",  // ©
        "\u{2117}", // ℗
        "(c) ",
        "(p) ",
        "all rights reserved",
        "lyrics licensed",
        "lyrics provided",
        "licensed and provided",
        "source: ",
        "songwriter:",
        "songwriters:",
        "producer:",
        "producers:",
        "writer:",
        "writers:",
        "writer(s):",
        "composer:",
        "composers:",
    ];
    if PREFIXES.iter().any(|p| l.starts_with(p)) {
        return true;
    }
    if l == "you might also like" || l == "embed" {
        return true; // Genius paste junk
    }
    // Genius first line: "23 Contributors…" / "23Contributors…"
    let after_digits = l.trim_start_matches(|c: char| c.is_ascii_digit());
    after_digits.len() < l.len() && after_digits.trim_start().starts_with("contributor")
}

/// Trailing repeat marker on a lyric line: `… (x2)`, `… [x3]`, `… x2`.
/// Returns (kept text, times, marker text as pasted).
fn split_trailing_repeat(line: &str) -> Option<(String, u32, String)> {
    let t = line.trim_end();
    if t.ends_with(')') || t.ends_with(']') {
        let open = if t.ends_with(')') { '(' } else { '[' };
        let start = t.rfind(open)?;
        let marker = &t[start..];
        let times = parse_repeat_marker(marker)?;
        return Some((t[..start].trim_end().to_string(), times, marker.to_string()));
    }
    let last_ws = t.rfind(char::is_whitespace)?;
    let tok = &t[last_ws + 1..];
    let times = parse_repeat_token(tok)?;
    Some((t[..last_ws].trim_end().to_string(), times, tok.to_string()))
}

/// Top-level `( … )` group byte ranges in a line (ad-lib candidates).
fn parenthetical_ranges(s: &str) -> Vec<(usize, usize)> {
    let mut out = Vec::new();
    let mut i = 0usize;
    while i < s.len() {
        if s[i..].starts_with('(') {
            if let Some((_, after)) = matching_close(&s[i..], '(', ')') {
                out.push((i, i + after));
                i += after;
                continue;
            }
            break; // unbalanced: no ad-lib flagging past this point
        }
        i += s[i..].chars().next().map(char::len_utf8).unwrap_or(1);
    }
    out
}

fn tokens_with_spans(s: &str) -> Vec<(usize, usize)> {
    let mut out = Vec::new();
    let mut start: Option<usize> = None;
    for (i, c) in s.char_indices() {
        if c.is_whitespace() {
            if let Some(st) = start.take() {
                out.push((st, i));
            }
        } else if start.is_none() {
            start = Some(i);
        }
    }
    if let Some(st) = start {
        out.push((st, s.len()));
    }
    out
}

// ---------------------------------------------------------------------------
// the cleanup pass
// ---------------------------------------------------------------------------

/// An open section (a header carrying a repeat count was seen; the section
/// runs until a blank line, the next header, or EOF, then gets duplicated).
struct OpenSection {
    name: String,
    times: u32,
    marker: String,
    header_line: usize,
    out_start: usize,
}

/// Run the cleanup pass. Never fails: unrecognized content is kept verbatim
/// (cleanup must not eat lyrics), and every change lands in `edits`.
pub fn clean(text: &str) -> CleanLyrics {
    let trailing_newline = text.ends_with('\n');
    let mut src: Vec<&str> = text.split('\n').collect();
    if trailing_newline {
        src.pop(); // the empty element after the final '\n'
    }
    let last_content_line = src
        .iter()
        .rposition(|l| !l.trim().is_empty())
        .unwrap_or(usize::MAX);

    let mut lines: Vec<CleanLine> = Vec::new();
    let mut edits: Vec<Edit> = Vec::new();
    let mut pending_blanks = 0usize;
    let mut stanza_start = 0usize; // output index where the current stanza began
    let mut section: Option<OpenSection> = None;

    let close_section = |section: &mut Option<OpenSection>,
                         lines: &mut Vec<CleanLine>,
                         edits: &mut Vec<Edit>| {
        if let Some(sec) = section.take() {
            let body: Vec<CleanLine> = lines[sec.out_start..].to_vec();
            if body.is_empty() || sec.times < 2 {
                return;
            }
            let mut added = 0usize;
            for _ in 1..sec.times {
                for (i, l) in body.iter().enumerate() {
                    let mut c = l.clone();
                    c.repeated = true;
                    c.blank_before = if i == 0 { 1 } else { 0 }; // each copy is a stanza
                    lines.push(c);
                    added += 1;
                }
            }
            edits.push(Edit::RepeatExpanded {
                line: sec.header_line,
                marker: sec.marker,
                times: sec.times,
                scope: RepeatScope::Section,
                section: Some(sec.name),
                lines_added: added,
            });
        }
    };

    for (idx, raw) in src.iter().enumerate() {
        let n = idx + 1; // 1-based source line number
        let line = raw.strip_suffix('\r').unwrap_or(raw);
        let trimmed = line.trim();

        // blank: stanza / section boundary
        if trimmed.is_empty() {
            close_section(&mut section, &mut lines, &mut edits);
            pending_blanks += 1;
            stanza_start = lines.len();
            continue;
        }

        // section header?
        if let Some((name, times)) = parse_header_line(line) {
            close_section(&mut section, &mut lines, &mut edits);
            edits.push(Edit::SectionHeaderRemoved {
                line: n,
                text: trimmed.to_string(),
            });
            if times >= 2 {
                section = Some(OpenSection {
                    name,
                    times,
                    marker: trimmed.to_string(),
                    header_line: n,
                    out_start: lines.len(),
                });
            }
            stanza_start = lines.len();
            continue;
        }

        // lone repeat marker line -> duplicate the stanza above it
        if let Some(times) = parse_repeat_marker(trimmed) {
            let body: Vec<CleanLine> = lines[stanza_start..].to_vec();
            let mut added = 0usize;
            for _ in 1..times {
                for l in &body {
                    let mut c = l.clone();
                    c.repeated = true;
                    c.blank_before = 0; // flows on within the stanza
                    lines.push(c);
                    added += 1;
                }
            }
            edits.push(Edit::RepeatExpanded {
                line: n,
                marker: trimmed.to_string(),
                times,
                scope: RepeatScope::Stanza,
                section: None,
                lines_added: added,
            });
            continue;
        }

        // credit / boilerplate line
        if is_credit_line(line) {
            edits.push(Edit::CreditLineRemoved {
                line: n,
                text: trimmed.to_string(),
            });
            continue;
        }

        // --- a kept lyric line ---
        let mut display = line.to_string();

        // Genius embed suffix glued to the last content line ("…gone42Embed")
        if idx == last_content_line && display.trim_end().ends_with("Embed") {
            let t = display.trim_end();
            let without = t.strip_suffix("Embed").unwrap_or(t);
            let without = without.trim_end_matches(|c: char| c.is_ascii_digit());
            let removed = t[without.len()..].to_string();
            edits.push(Edit::EmbedSuffixRemoved {
                line: n,
                text: removed,
            });
            display = without.to_string();
            if display.trim().is_empty() {
                continue; // the whole line was junk
            }
        }

        // trailing repeat marker -> the line repeats
        let mut line_times = 1u32;
        let mut line_marker = String::new();
        if let Some((rest, times, marker)) = split_trailing_repeat(&display) {
            if !rest.trim().is_empty() {
                display = rest;
                line_times = times;
                line_marker = marker;
            }
        }

        // parenthetical ad-libs: flag, keep verbatim
        let ranges = parenthetical_ranges(&display);
        for &(s, e) in &ranges {
            edits.push(Edit::AdLibFlagged {
                line: n,
                text: display[s..e].to_string(),
            });
        }
        let words: Vec<CleanWord> = tokens_with_spans(&display)
            .into_iter()
            .map(|(s, e)| CleanWord {
                display: display[s..e].to_string(),
                ad_lib: ranges.iter().any(|&(rs, re)| s < re && e > rs),
            })
            .collect();

        let clean_line = CleanLine {
            display,
            words,
            source_line: n,
            blank_before: std::mem::take(&mut pending_blanks),
            repeated: false,
        };
        lines.push(clean_line);
        if line_times >= 2 {
            let template = lines.last().expect("just pushed").clone();
            let mut added = 0usize;
            for _ in 1..line_times {
                let mut c = template.clone();
                c.repeated = true;
                c.blank_before = 0;
                lines.push(c);
                added += 1;
            }
            edits.push(Edit::RepeatExpanded {
                line: n,
                marker: line_marker,
                times: line_times,
                scope: RepeatScope::Line,
                section: None,
                lines_added: added,
            });
        }
    }
    close_section(&mut section, &mut lines, &mut edits);

    CleanLyrics {
        lines,
        edits,
        trailing_newline,
    }
}

// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn displays(c: &CleanLyrics) -> Vec<&str> {
        c.lines.iter().map(|l| l.display.as_str()).collect()
    }

    // -- headers --

    #[test]
    fn bracket_header_variants_are_stripped() {
        for h in [
            "[Chorus]",
            "[Verse 2]",
            "[Bridge: Fictional Artist]",
            "[Verse 2: Someone & Someone Else]",
            "(Chorus)",
            "{Hook}",
            "[PRE-CHORUS]",
            "[Pre-Chorus 2]",
            "[Part II]",
        ] {
            let c = clean(&format!("{h}\nmoonlight on the water\n"));
            assert_eq!(displays(&c), vec!["moonlight on the water"], "header {h}");
            assert!(
                matches!(c.edits[0], Edit::SectionHeaderRemoved { line: 1, .. }),
                "header {h} -> {:?}",
                c.edits
            );
        }
    }

    #[test]
    fn bare_colon_header_is_stripped() {
        let c = clean("Chorus:\nsailing home again\n");
        assert_eq!(displays(&c), vec!["sailing home again"]);
        assert_eq!(c.edits.len(), 1);
    }

    #[test]
    fn bare_keyword_without_colon_is_kept() {
        // could be a lyric word — conservative rule requires the colon
        let c = clean("Chorus\nsailing home again\n");
        assert_eq!(displays(&c), vec!["Chorus", "sailing home again"]);
        assert!(c.edits.is_empty());
    }

    #[test]
    fn non_header_bracket_line_is_kept() {
        let c = clean("[?]\nmystery line\n");
        assert_eq!(displays(&c), vec!["[?]", "mystery line"]);
    }

    // -- repeat markers --

    #[test]
    fn trailing_line_markers_expand() {
        for m in ["(x2)", "(2x)", "[x2]", "x2", "X2", "\u{d7}2", "(\u{d7}2)"] {
            let c = clean(&format!("row the boat ashore {m}\n"));
            assert_eq!(
                displays(&c),
                vec!["row the boat ashore", "row the boat ashore"],
                "marker {m}"
            );
            assert!(c.lines[1].repeated && !c.lines[0].repeated);
            assert_eq!(c.lines[1].source_line, 1); // provenance
            assert!(matches!(
                c.edits[0],
                Edit::RepeatExpanded {
                    times: 2,
                    scope: RepeatScope::Line,
                    ..
                }
            ));
        }
    }

    #[test]
    fn x3_repeats_three_times_and_x99_is_clamped() {
        let c = clean("hey now [x3]\n");
        assert_eq!(c.lines.len(), 3);
        let c = clean("hey now (x99)\n");
        assert_eq!(c.lines.len(), MAX_REPEAT as usize);
    }

    #[test]
    fn lone_marker_line_repeats_the_stanza() {
        let c = clean("first light\nsecond sight\nx2\n\nnext stanza\n");
        assert_eq!(
            displays(&c),
            vec![
                "first light",
                "second sight",
                "first light",
                "second sight",
                "next stanza"
            ]
        );
        assert!(matches!(
            c.edits[0],
            Edit::RepeatExpanded {
                line: 3,
                scope: RepeatScope::Stanza,
                lines_added: 2,
                ..
            }
        ));
    }

    #[test]
    fn header_marker_repeats_the_section() {
        let c = clean("[Chorus x2]\ngolden hour\nfading now\n\n[Verse 3]\nonward\n");
        assert_eq!(
            displays(&c),
            vec![
                "golden hour",
                "fading now",
                "golden hour",
                "fading now",
                "onward"
            ]
        );
        let rep = c
            .edits
            .iter()
            .find(|e| matches!(e, Edit::RepeatExpanded { .. }))
            .unwrap();
        match rep {
            Edit::RepeatExpanded {
                scope, section, ..
            } => {
                assert_eq!(*scope, RepeatScope::Section);
                assert_eq!(section.as_deref(), Some("chorus"));
            }
            _ => unreachable!(),
        }
        assert!(c.summary().contains("expanded one x2 chorus"), "{}", c.summary());
    }

    #[test]
    fn header_with_marker_outside_brackets() {
        let c = clean("[Chorus] (x2)\nla la line\n");
        assert_eq!(displays(&c), vec!["la la line", "la la line"]);
    }

    #[test]
    fn section_repeat_ends_at_next_header() {
        let c = clean("[Chorus x2]\nchorus line\n[Outro]\nlast words\n");
        assert_eq!(
            displays(&c),
            vec!["chorus line", "chorus line", "last words"]
        );
    }

    #[test]
    fn line_repeat_nested_in_repeated_section() {
        // the x2 line expands first, then the section copy duplicates the
        // already-expanded body
        let c = clean("[Chorus x2]\necho me (x2)\nsolid ground\n");
        assert_eq!(
            displays(&c),
            vec![
                "echo me",
                "echo me",
                "solid ground",
                "echo me",
                "echo me",
                "solid ground"
            ]
        );
        assert_eq!(
            c.edits
                .iter()
                .filter(|e| matches!(e, Edit::RepeatExpanded { .. }))
                .count(),
            2
        );
    }

    #[test]
    fn ordinary_words_ending_in_x_are_not_markers() {
        let c = clean("in a box\nfeeling lax\n");
        assert!(c.edits.is_empty());
        assert_eq!(c.lines.len(), 2);
    }

    // -- ad-libs --

    #[test]
    fn inline_adlib_is_flagged_and_kept_verbatim() {
        let c = clean("driving all night (oh yeah) to see you\n");
        assert_eq!(displays(&c), vec!["driving all night (oh yeah) to see you"]);
        let flags: Vec<bool> = c.lines[0].words.iter().map(|w| w.ad_lib).collect();
        assert_eq!(
            flags,
            vec![false, false, false, true, true, false, false, false]
        );
        assert!(matches!(&c.edits[0], Edit::AdLibFlagged { line: 1, text } if text == "(oh yeah)"));
    }

    #[test]
    fn whole_line_parenthetical_is_adlib_not_header() {
        let c = clean("(woo)\nreal line\n");
        assert_eq!(displays(&c), vec!["(woo)", "real line"]);
        assert!(c.lines[0].words[0].ad_lib);
        assert!(matches!(c.edits[0], Edit::AdLibFlagged { .. }));
    }

    #[test]
    fn adlib_and_trailing_repeat_coexist() {
        let c = clean("shine on (shine on) x2\n");
        assert_eq!(displays(&c), vec!["shine on (shine on)", "shine on (shine on)"]);
        assert!(c.lines[0].words[2].ad_lib && c.lines[0].words[3].ad_lib);
    }

    // -- credit / boilerplate lines --

    #[test]
    fn credit_lines_are_stripped() {
        for l in [
            "Produced by Fictional Producer",
            "Lyrics by A. Nobody",
            "Written by Someone",
            "\u{a9} 2026 Made-Up Records",
            "(c) 2026 Made-Up Records",
            "All rights reserved. International copyright secured.",
            "Lyrics licensed and provided by ExampleFind",
            "You might also like",
            "23 ContributorsMade-Up Song Lyrics",
            "Embed",
        ] {
            let c = clean(&format!("{l}\nkept lyric line\n"));
            assert_eq!(displays(&c), vec!["kept lyric line"], "credit {l}");
            assert!(
                matches!(c.edits[0], Edit::CreditLineRemoved { line: 1, .. }),
                "credit {l} -> {:?}",
                c.edits
            );
        }
    }

    #[test]
    fn embed_suffix_on_last_line_is_stripped() {
        let c = clean("first line\nand then I'm gone42Embed");
        assert_eq!(displays(&c), vec!["first line", "and then I'm gone"]);
        assert!(matches!(&c.edits[0], Edit::EmbedSuffixRemoved { line: 2, text } if text == "42Embed"));
    }

    #[test]
    fn lyric_mentioning_produced_mid_sentence_is_kept() {
        let c = clean("we produced by hand a little dream\n");
        assert_eq!(c.lines.len(), 1);
        assert!(c.edits.is_empty());
    }

    // -- unicode --

    #[test]
    fn smart_quotes_and_unicode_punct_survive_verbatim() {
        let text = "don\u{2019}t say \u{201c}goodbye\u{201d} \u{2014} stay\n";
        let c = clean(text);
        assert_eq!(c.to_text(), text);
        assert_eq!(c.lines[0].words[0].display, "don\u{2019}t");
    }

    // -- passthrough & reconstruction --

    #[test]
    fn clean_file_passes_through_byte_identical() {
        let text = "over the hills we wander\nthrough the pines we roam\n\nevery star a lantern\nleading us back home\n";
        let c = clean(text);
        assert!(c.edits.is_empty());
        assert_eq!(c.to_text(), text);
        assert_eq!(c.lines[2].blank_before, 1); // stanza break preserved
    }

    #[test]
    fn crlf_input_is_tolerated() {
        let c = clean("[Chorus]\r\nline one\r\nline two\r\n");
        assert_eq!(displays(&c), vec!["line one", "line two"]);
    }

    #[test]
    fn no_trailing_newline_is_preserved() {
        let text = "line one\nline two";
        assert_eq!(clean(text).to_text(), text);
    }

    // -- summary & structure --

    #[test]
    fn summary_counts_read_naturally() {
        let c = clean(
            "[Verse 1]\nfirst line\n\n[Chorus]\nsecond line (x2)\n\n[Outro]\n(hey)\nProduced by Nobody\n",
        );
        let s = c.summary();
        assert!(s.contains("removed 3 section headers"), "{s}");
        assert!(s.contains("removed 1 credit/boilerplate line"), "{s}");
        assert!(s.contains("expanded one x2 line"), "{s}");
        assert!(s.contains("flagged 1 ad-lib"), "{s}");
    }

    #[test]
    fn summary_no_changes() {
        assert_eq!(clean("plain line\n").summary(), "no changes needed");
    }

    #[test]
    fn lyric_words_flatten_with_anchor_norms() {
        let c = clean("Don\u{2019}t stop (woo)\n");
        let w = c.lyric_words();
        assert_eq!(w.len(), 3);
        assert_eq!(w[0].display, "Don\u{2019}t");
        assert_eq!(w[0].norm, "DON'T"); // anchor.rs folding, not duplicated here
    }

    #[test]
    fn edit_display_renders_line_references() {
        let c = clean("[Chorus]\nhello\n");
        let rendered = format!("{}", c.edits[0]);
        assert!(rendered.contains("line 1"), "{rendered}");
    }
}
